version: '2'
services:

### Nginx ###
    webserver:
      image: nginx:1.14.0-alpine
      container_name: nginx_1.14
      links:
        - app
      ports:
        - "80:80"
      volumes:
        - ./web/default.conf:/etc/nginx/conf.d/default.conf
        - ./src:/var/www/html:cached 

### PHP ###
    app:
      build: ./php
      container_name: php_fpm
      links:
        - dbserver
      volumes:
        - ./src:/var/www/html:cached 

### MySQL###
    dbserver:
      build: ./db
      container_name: mysql_8
      ports: 
        - "3036:3036"
      environment:
        - MYSQL_ROOT_PASSWORD=password
        - MYSQL_DATABASE=test
        - MYSQL_USER=test
        - MYSQL_PASSWORD=test
      volumes_from:
        - data

### 保存領域 ###
    data:
      image: busybox
      container_name: db_container
